<a href="https://colab.research.google.com/github/anggaagustiratelkom/data_scientist/blob/TugasPertemuan4/Pertemuan_4_Tugas_Mandiri_Microcredential_Angga.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![header%20ipynb.png](attachment:header%20ipynb.png)

# Hands-On

Hands-On ini digunakan pada kegiatan Microcredential Associate Data Scientist 2021

# Definisi Matriks

Matriks dalam dunia metematika merupakan suatu bilangan, simbol, ataupun ekspresi yang disusun dalam baris dan kolom yang membentuk suatu bidang persegi/persegi panjang. Matriks memiliki ukuran/orde. Pada Python, matriks dapat dibuat sesuai kebutuhan dengan menentukan ukuran/orde dari matriks. Bentuk umum ukuran/orde matriks adalah mxn, m adalah banyak baris dan n adalah banyak kolom.

# Contoh Membuat Matriks Orde 2x2
Berikut ini adalah syntax untuk membuat sebuah matriks yang diberi nama matriksA dengan ukuran/orde 2x2. Matriks orde 2x2 merupakan matriks yang memiliki nilai pada 2 baris dan 2 kolom. 
Pada contoh: 
matriksA memiliki:
Baris 1 Kolom 1, nilai = 1
Baris 1 Kolom 2, nilai = 0
Baris 2 Kolom 1, nilai = 0
Baris 2 Kolom 2, nilai = 1

In [ ]:
#Matriks dengan ukuran 2x2
matriksA = [ [1,0],[0,1] ]
#Menampilkan matriks dengan nama matriksA
print (matriksA)

[[1, 0], [0, 1]]


# Contoh Membuat Matriks Orde 3x3
Berikut ini adalah syntax untuk membuat sebuah matriks yang diberi nama matriksB dengan ukuran/orde 3x3. Matriks orde 3x3 merupakan matriks yang memiliki nilai pada 3 baris dan 3 kolom. 
Pada contoh: 
matriksB memiliki:
Baris 1 Kolom 1, nilai = 1
Baris 1 Kolom 2, nilai = 0
Baris 1 Kolom 3, nilai = 1
Baris 2 Kolom 1, nilai = 0
Baris 2 Kolom 2, nilai = 1
Baris 2 Kolom 3, nilai = 0
Baris 3 Kolom 1, nilai = 1
Baris 3 Kolom 2, nilai = 0
Baris 3 Kolom 3, nilai = 1

In [ ]:
#Matriks dengan ukuran 3x3
matriksB = [ [1,0,1],[0,1,0],[1,0,1] ]
#Menampilkan matriks dengan nama MatriksB
print (matriksB)

[[1, 0, 1], [0, 1, 0], [1, 0, 1]]


# Latihan (1)
Buatlah matriksC dengan orde 2x3, dan nilai yang diberikan pada matriksC adalah sebagai berikut:
Baris 1 Kolom 1, nilai = 1
Baris 1 Kolom 2, nilai = 2
Baris 1 Kolom 3, nilai = 3
Baris 2 Kolom 1, nilai = 4
Baris 2 Kolom 2, nilai = 5
Baris 2 Kolom 3, nilai = 6

In [ ]:
#Latihan(1)
#Matriks dengan ukuran 2x3
matriksC = [ [1,2,3],[4,5,6] ]

#Menampilkan matriks dengan nama MatriksC
print (matriksC)

[[1, 2, 3], [4, 5, 6]]


# Membuat Matriks dengan Menggunakan Perulangan
Matriks dapat juga dibuat dengan menggunakan fungsi perulangan.
Fungsi perulangan atau biasa disebut looping atau iterasi memerlukan tes kondisi. Bila hasil tes kondisi True, maka blok kode kembali dieksekusi. Tapi jika False, maka keluar dari perulangan.
Di python, perulangan bisa dilakukan dengan dua cara atau metode, yaitu: menggunakan For atau menggunakan While.

# Contoh Membuat Matriks dengan Perulangan FOR
Pada contoh berikut ini, dibuat matriks dengan menggunakan perulangan for. Matriks mempunyai orde mxn, yaitu: orde 2x3, dan nilai yang diberikan adalah:
Baris 1 Kolom 1, nilai = 1
Baris 1 Kolom 2, nilai = 1
Baris 1 Kolom 3, nilai = 1
Baris 2 Kolom 1, nilai = 1
Baris 2 Kolom 2, nilai = 1
Baris 2 Kolom 3, nilai = 1

In [ ]:
#Matriks dengan menggunakan fungsi perulangan
m = 2
n = 3 
x = [0]*m
#Fungsi perulangan dengan menggunakan for
for i in range(m): 
    x[i] = [1]*n 
#Menampilkan matriks
print (x)

[[1, 1, 1], [1, 1, 1]]


# Latihan (2)
Buatlah matriks dengan orde 3x2, dengan nilai adalah:
Baris 1 Kolom 1, nilai = 2
Baris 1 Kolom 2, nilai = 2
Baris 2 Kolom 1, nilai = 2
Baris 2 Kolom 2, nilai = 2
Baris 3 Kolom 1, nilai = 2
Baris 3 Kolom 2, nilai = 2

In [ ]:
#Latihan(2)
#Matriks dengan menggunakan fungsi perulangan
o = 3
p = 2
y = [0]*o

#Fungsi perulangan dengan menggunakan for
for i in range(o): 
    y[i] = [2]*p 

#Menampilkan matriks
print (y)

[[2, 2], [2, 2], [2, 2]]


# Membuat Matriks dengan Menggunakan Library Numpy
Library pada Python merupakan sebutan untuk kode program tambahan yang digunakan dalam kebutuhan tertentu. Python mempunyai lebih dari 140.000 library yang dikembangkan melalui open source project.

Library Numpy memiliki kegunaan untuk operasi vektor dan matriks. Fiturnya hampir sama dengan MATLAB dalam mengelola array dan array multidimensi. Numpy merupakan salah satu library yang digunakan oleh library lain seperti Scikit-Learn untuk keperluan analisis data.

# Contoh Membuat Matriks dengan Numpy
Pada contoh berikut dibuat matriks dengan panjang elemen sebanyak 12 dengan nilai elemen dimulai dari indeks 0 sampai 11, dengan ukuran/orde matriks adalah 4x3.

In [ ]:
#Panggil Library Numpy
from numpy import * 
#Menentukan panjang elemen sebanyak 12
matriks = range(12) 
#Matriks orde adalah 4x3
matriks = reshape(matriks,(4,3)) 
#Menampilkan matriks
print (matriks)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


# Latihan (3)
Buatlah matriks dengan menggunakan Library Numpy dengan panjang elemen adalah 32 dan matriks memiliki orde 4x8

In [ ]:
#Latihan(3)
#Panggil Library Numpy
from numpy import * 

#Menentukan panjang elemen sebanyak 32
matriks = range(32) 

#Matriks orde adalah 4x8
matriks = reshape(matriks,(4,8)) 

#Menampilkan matriks
print (matriks)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


# Membuat Matriks dengan Nilai Random
Jika ingin elemen pada matriks bernilai random, dapat menggunakan fungsi random yang tersedia pada numpy.

# Contoh Membuat Matriks Random dengan Numpy
Pada contoh berikut ini dibuat matriks dengan ukuran/orde 3x4 dengan nilai elemen dimulai dari indeks 1 sampai 4 secara random. 

In [ ]:
#Memanggil Library numpy dan diberikan nama alias np
import numpy as np
#Membuat matriks ukuran 3x4 dengan random

matriks = np.random.randint(1,4,(3,4))
#Menampilkan matriks
print (matriks)

[[2 3 2 3]
 [1 1 2 2]
 [3 1 2 1]]


# Latihan (4)
Buatlah matriks dengan menggunakan Library Numpy dengan orde 3x30, dan nilai elemen dimulai dari indeks 1 sampai dengan 5 secara random.

In [ ]:
#Latihan(4)
#Memanggil Library numpy dan diberikan nama alias np
import numpy as np

#Membuat matriks ukuran 3x30 dengan random
matriks = np.random.randint(1,5,(3,30))

#Menampilkan matriks
print (matriks)

[[3 1 1 4 3 4 4 3 4 1 1 1 4 4 3 3 3 1 4 1 2 2 1 1 2 1 3 3 2 1]
 [3 4 3 3 4 1 3 2 1 4 2 3 4 4 1 3 4 3 3 2 4 2 1 2 3 2 1 2 3 1]
 [4 4 1 2 3 3 3 3 2 3 2 2 4 1 3 4 4 1 4 4 2 1 4 3 3 2 3 1 1 2]]


# Penjumlahan Matriks

Penjumlahan matriks dilakukan dengan menjumlahkan setiap elemen, menggunakan tanda plus (+). Hasil penjumlahan tersebut akan menjadi elemen baru. Masing - masing matriks diakses setiap elemennya pada koordinat yang sama kemudian dijumlahkan untuk mendapatkan elemen baru. Penjumlahan matriks dilakukan pada dua buah matriks yang memiliki orde sama.

In [ ]:
#Penjumlahan Matriks
#Contoh 1
mat1 = [
    [5, 0],
    [2, 6],
]

mat2 = [
    [1, 0],
    [4, 2],
]


for x in range(0, len(mat1)):
    for y in range(0, len(mat1[0])):
        print (mat1[x][y] + mat2[x][y], end=' '),
    print

6 0 6 8 

In [ ]:
#Penjumlahan Matriks
#Contoh 2
import numpy as np
matriksA = np.random.randint(1, 4,(3, 4))
matriksB = np.random.randint(1, 3,(3, 4))
print (matriksA)
print () #memberikan spasi baris pada matriks yang tercetak
print (matriksB)
print ()

#penjumlahan matriksA dan matriks B
for x in range(0, len(matriksA)):
    print ('Hasil Penjumlahan matriksA dan matriksB', 'Baris ke-', x+1)
    print ()
    for y in range(0, len(matriksA[0])):
        print (matriksA[x][y] + matriksB[x][y], end=' '),
    print ()

[[1 2 2 2]
 [3 1 3 3]
 [3 2 3 3]]

[[2 2 2 1]
 [1 2 1 2]
 [2 2 1 2]]

Hasil Penjumlahan matriksA dan matriksB Baris ke- 1

3 4 4 3 
Hasil Penjumlahan matriksA dan matriksB Baris ke- 2

4 3 4 5 
Hasil Penjumlahan matriksA dan matriksB Baris ke- 3

5 4 4 5 


In [ ]:
#Penjumlahan Matriks
#Contoh 3
import numpy as np
matriksA = np.random.randint(1, 4,(6, 10))
matriksB = np.random.randint(1, 3,(6, 10))
print (matriksA)
print () #memberikan spasi baris pada matriks yang tercetak
print (matriksB)
print ()

#penjumlahan matriksA dan matriks B
for x in range(0, len(matriksA)):
    print ()
    for y in range(0, len(matriksA[0])):
        print (matriksA[x][y] + matriksB[x][y], end=' '),
    print ()

[[3 2 3 3 2 3 3 2 3 1]
 [3 2 1 1 2 3 2 2 3 3]
 [3 1 2 3 1 3 3 1 2 3]
 [3 3 2 3 1 1 3 1 2 1]
 [3 1 1 1 2 2 3 1 1 3]
 [2 2 2 3 2 3 2 2 2 3]]

[[1 2 1 1 1 1 1 2 1 1]
 [2 1 2 2 1 1 1 2 1 2]
 [1 2 2 1 2 1 1 1 1 2]
 [1 1 2 2 2 1 2 1 1 1]
 [2 1 2 2 2 2 2 2 1 1]
 [2 2 1 1 2 2 1 2 2 2]]


4 4 4 4 3 4 4 4 4 2 

5 3 3 3 3 4 3 4 4 5 

4 3 4 4 3 4 4 2 3 5 

4 4 4 5 3 2 5 2 3 2 

5 2 3 3 4 4 5 3 2 4 

4 4 3 4 4 5 3 4 4 5 


# Latihan (5)

Buatlah penjumlahan dua matriks dengan menggunakan library Numpy, dengan matriks berukuran 7x9 yang nilainya didapatkan secara random.

In [ ]:
#Latihan(5)
#Penjumlahan Matriks
import numpy as np
matriksA = np.random.randint(1, 4,(7, 9))
matriksB = np.random.randint(1, 4,(7, 9))
print (matriksA)
print () #memberikan spasi baris pada matriks yang tercetak
print (matriksB)
print ()

#penjumlahan matriksA dan matriks B
for x in range(0, len(matriksA)):
    print ()
    for y in range(0, len(matriksA[0])):
        print (matriksA[x][y] + matriksB[x][y], end=' '),
    print ()

[[3 3 1 3 3 1 1 2 3]
 [1 2 1 1 1 1 2 3 1]
 [2 1 2 2 3 2 3 3 3]
 [1 3 2 2 2 1 3 3 1]
 [1 1 1 3 1 3 1 2 3]
 [1 1 3 3 3 3 3 3 1]
 [3 1 1 2 3 1 1 1 2]]

[[1 3 3 2 3 2 2 3 2]
 [3 2 3 3 1 1 2 2 1]
 [2 1 2 2 3 2 2 2 1]
 [1 3 2 2 2 2 3 2 1]
 [1 1 1 1 3 3 2 2 3]
 [2 3 2 3 1 3 2 1 2]
 [3 3 2 2 3 1 2 2 3]]


4 6 4 5 6 3 3 5 5 

4 4 4 4 2 2 4 5 2 

4 2 4 4 6 4 5 5 4 

2 6 4 4 4 3 6 5 2 

2 2 2 4 4 6 3 4 6 

3 4 5 6 4 6 5 4 3 

6 4 3 4 6 2 3 3 5 


# Pengurangan Matriks

Pengurangan matriks menggunakan operator dengan tanda kurang (-). Matriks baru akan terbentuk sebagai hasil dari pengurangan setiap kedua elemen matriks. Pengurangan matriks dilakukan pada dua matriks yang memiliki orde yang sama.

In [ ]:
#Pengurangan Matriks
#Contoh 1
mat1 = [
    [5, 0],
    [2, 6],
]

mat2 = [
    [1, 0],
    [4, 2],
]


for x in range(0, len(mat1)):
    for y in range(0, len(mat1[0])):
        print (mat1[x][y] - mat2[x][y], end=' '),
    print

In [ ]:
#Pengurangan Matriks
#Contoh 2
mat1 = [
    [5, 0],
    [2, 6],
]

mat2 = [
    [1, 0],
    [4, 2],
]


for x in range(0, len(mat1)):
    for y in range(0, len(mat1[0])):
        print (mat1[x][y] - mat2[x][y], end=' '),
    print ()

In [ ]:
#Pengurangan Matriks
#Contoh 3
import numpy as np
matriksA = np.random.randint(1, 4,(3, 4))
matriksB = np.random.randint(1, 3,(3, 4))
print (matriksA)
print () #memberikan spasi baris pada matriks yang tercetak
print (matriksB)
print ()

#pengurangan matriksA dengan matriks B
for x in range(0, len(matriksA)):
    print ('Hasil Pengurangan matriksA dan matriksB', 'Baris ke-', x+1)
    print ()
    for y in range(0, len(matriksA[0])):
        print (matriksA[x][y] - matriksB[x][y], end=' '),
    print ()

In [ ]:
#Pengurangan Matriks
#Contoh 4
import numpy as np
matriksA = np.random.randint(1, 4,(6, 10))
matriksB = np.random.randint(1, 3,(6, 10))
print (matriksA)
print () #memberikan spasi baris pada matriks yang tercetak
print (matriksB)
print ()

#pengurangan matriksA dengan matriks B
for x in range(0, len(matriksA)):
    print ()
    for y in range(0, len(matriksA[0])):
        print (matriksA[x][y] - matriksB[x][y], end=' '),
    print ()

# Latihan (6)

Buatlah pengurangan dua matriks dengan menggunakan library Numpy, dengan matriks berukuran 7x9 yang nilainya didapatkan secara random.

In [ ]:
#Latihan(6)
#Pengurangan Matriks
import numpy as np
matriksA = np.random.randint(1, 10,(7, 9))
matriksB = np.random.randint(1, 10,(7, 9))
print (matriksA)
print () #memberikan spasi baris pada matriks yang tercetak
print (matriksB)
print ()

#pengurangan matriksA dengan matriks B
for x in range(0, len(matriksA)):
    print ()
    for y in range(0, len(matriksA[0])):
        print (matriksA[x][y] - matriksB[x][y], end=' '),
    print ()

[[4 2 8 1 2 9 1 4 2]
 [5 7 9 6 9 1 2 9 5]
 [5 2 7 6 4 7 7 8 1]
 [9 2 8 8 1 5 8 2 4]
 [2 3 4 4 7 7 7 4 8]
 [1 3 8 1 4 7 4 9 8]
 [8 5 9 6 3 7 7 6 2]]

[[5 6 4 8 7 7 5 6 5]
 [2 5 9 8 2 9 3 3 3]
 [7 1 8 8 5 8 5 7 8]
 [7 2 3 3 7 5 2 4 1]
 [7 1 7 4 7 4 7 2 8]
 [9 5 7 7 8 8 5 2 3]
 [7 7 2 8 3 5 2 3 3]]


-1 -4 4 -7 -5 2 -4 -2 -3 

3 2 0 -2 7 -8 -1 6 2 

-2 1 -1 -2 -1 -1 2 1 -7 

2 0 5 5 -6 0 6 -2 3 

-5 2 -3 0 0 3 0 2 0 

-8 -2 1 -6 -4 -1 -1 7 5 

1 -2 7 -2 0 2 5 3 -1 


# Penggunaan Library Pandas

# Latihan (7)

Lakukan import Library Pandas

In [ ]:
#Latihan(7)
#Import Library Pandas

...............

# Latihan (8)

Panggil file dengan format .csv yang bernama "cloth_data"

In [ ]:
#latihan(8)
#Panggil file bernama cloth_data.csv

...............

# Latihan (9)

Tampilkan data dari "cloth_data" 

In [ ]:
#latihan(9)
#Tampilkan data dari dataset cloth_data 

...............

# Latihan (10)

Tampilkan data dari "cloth_data" mulai dari indeks 0 (nol) sampai dengan indeks 10 (sepuluh)

In [ ]:
#Latihan(10)
#Tampilkan data dari "cloth_data" mulai dari indeks 0 (nol) sampai dengan indeks 10 (sepuluh)

...............


# Latihan (11)

Tampilkan data dari "cloth_data" untuk kolom age dan size

In [ ]:
#Latihan(11)
#Tampilkan data dari "cloth_data" untuk kolom age dan size

...............

# Latihan (12)

Tampilkan data dari "cloth_data" untuk kolom age dan size, mulai dari indeks 0 (nol) sampai dengan indeks 10 (sepuluh)

In [ ]:
#Latihan(12)
#Tampilkan data dari "cloth_data" untuk kolom age dan size, mulai dari indeks 0 (nol) sampai dengan indeks 10 (sepuluh)

...............

# Penggunaan Library Matplotlib

# Latihan (13)

Lakukan import Library Matplotlib

In [ ]:
#Latihan(13)
#Import Library Matplotlib

...............

# Latihan (14)

Buatlah visualisasi dalam bentuk histogram pada data "cloth_data" untuk kolom size

In [ ]:
#Latihan(14)
#Buat histogram untuk kolom size

...............

# Latihan (15)

Buatlah visualisasi dalam bentuk grafik (plot) pada data "cloth_data" untuk kolom age dan kolom size

In [ ]:
#Latihan(15)
#Visualisasi dalam bentuk grafik (plot) pada data "cloth_data" untuk kolom age dan kolom size

...............

# Latihan (16)

Buatlah visualisasi dalam bentuk grafik (plot) pada data "cloth_data" untuk kolom size dan kolom age

In [ ]:
#Latihan(16)
#Visualisasi dalam bentuk grafik (plot) pada data "cloth_data" untuk kolom size dan kolom age

...............

# Latihan (17)

Import library seaborn

In [ ]:
#Latihan(17)
#Import library seaborn

...............

# Latihan (18)

Buatlah visualisasi dalam bentuk scatterplot pada data "cloth_data" untuk kolom age dan kolom size

In [ ]:
#latihan(18)
#Buat scatterplot dengan kolom age dan size

............

# Latihan (19)

Buatlah visualisasi dalam bentuk scatterplot pada data "cloth_data" untuk kolom size dan kolom age

In [ ]:
#latihan(19)
#Buat scatterplot dengan kolom size dan age

.....................

# Latihan (20)

Buatlah visualisasi dalam bentuk histogram pada data "cloth_data" untuk kolom age

In [ ]:
#Latihan(20)
#Buat histogram untuk kolom size

....................